name: Package Addon
on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.WOW_PAT }}

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WOW_PAT }}

      - name: Package and Release
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.WOW_PAT }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}